-- 持久化内置 LLM Provider 元数据；API Key 在后台 LLM 供应商页面保存。
DELETE FROM `global_env_config` WHERE `config_key` LIKE 'agent.ai.providers.zhipufree.%';

INSERT INTO `global_env_config` (`config_key`, `config_value`, `config_desc`, `config_type`, `enabled`, `priority`) VALUES
('agent.ai.providers.zhipu.api-style', 'openai', '智谱 API 风格', 'string', 1, 100),
('agent.ai.providers.zhipu.base-url', 'https://open.bigmodel.cn/api/paas/v4', '智谱 Base URL', 'string', 1, 100),
('agent.ai.providers.zhipu.completions-path', '/chat/completions', '智谱对话路径', 'string', 1, 100),
('agent.ai.providers.zhipu.models[0].name', 'glm-4.7', '智谱文本模型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[0].type', 'TEXT', '智谱文本模型类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[0].multimodal', 'false', '智谱模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.zhipu.models[0].billing-type', 'FREE', '智谱模型计费类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[1].name', 'glm-4.6v-flash', '智谱免费视觉模型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[1].type', 'VISION', '智谱视觉模型类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[1].multimodal', 'true', '智谱模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.zhipu.models[1].billing-type', 'FREE', '智谱模型计费类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[2].name', 'glm-5.2', '智谱付费文本模型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[2].type', 'TEXT', '智谱文本模型类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[2].multimodal', 'false', '智谱模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.zhipu.models[2].billing-type', 'PAID', '智谱模型计费类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[3].name', 'glm-5v-turbo', '智谱付费视觉模型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[3].type', 'VISION', '智谱视觉模型类型', 'string', 1, 100),
('agent.ai.providers.zhipu.models[3].multimodal', 'true', '智谱模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.zhipu.models[3].billing-type', 'PAID', '智谱模型计费类型', 'string', 1, 100),
('agent.ai.providers.silicon.api-style', 'openai', '硅基流动 API 风格', 'string', 1, 100),
('agent.ai.providers.silicon.base-url', 'https://api.siliconflow.cn', '硅基流动 Base URL', 'string', 1, 100),
('agent.ai.providers.silicon.completions-path', '/v1/chat/completions', '硅基流动对话路径', 'string', 1, 100),
('agent.ai.providers.silicon.embeddings-path', '/v1/embeddings', '硅基流动嵌入路径', 'string', 1, 100),
('agent.ai.providers.silicon.images-path', '/v1/images/embeddings', '硅基流动图片路径', 'string', 1, 100),
('agent.ai.providers.silicon.models[0].name', 'Qwen/Qwen2.5-7B-Instruct', '硅基流动文本模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[0].type', 'TEXT', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[0].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[1].name', 'Qwen/Qwen3.5-4B', '硅基流动文本模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[1].type', 'TEXT', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[1].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[2].name', 'Qwen/Qwen3-8B', '硅基流动文本模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[2].type', 'TEXT', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[2].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[3].name', 'PaddlePaddle/PaddleOCR-VL-1.5', '硅基流动视觉模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[3].type', 'VISION', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[3].multimodal', 'true', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[4].name', 'deepseek-ai/DeepSeek-OCR', '硅基流动视觉模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[4].type', 'VISION', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[4].multimodal', 'true', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[5].name', 'Kwai-Kolors/Kolors', '硅基流动生图模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[5].type', 'IMAGE', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[5].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[6].name', 'TeleAI/TeleSpeechASR', '硅基流动语音识别模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[6].type', 'ASR', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[6].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[7].name', 'FunAudioLLM/SenseVoiceSmall', '硅基流动语音识别模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[7].type', 'ASR', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[7].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[8].name', 'BAAI/bge-m3', '硅基流动嵌入模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[8].type', 'EMBEDDING', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[8].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[9].name', 'netease-youdao/bce-embedding-base_v1', '硅基流动嵌入模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[9].type', 'EMBEDDING', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[9].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.silicon.models[10].name', 'BAAI/bge-large-zh-v1.5', '硅基流动嵌入模型', 'string', 1, 100),
('agent.ai.providers.silicon.models[10].type', 'EMBEDDING', '硅基流动模型类型', 'string', 1, 100),
('agent.ai.providers.silicon.models[10].multimodal', 'false', '硅基流动模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.deepseek.api-style', 'openai', 'DeepSeek API 风格', 'string', 1, 100),
('agent.ai.providers.deepseek.base-url', 'https://api.deepseek.com', 'DeepSeek Base URL', 'string', 1, 100),
('agent.ai.providers.deepseek.completions-path', '/chat/completions', 'DeepSeek 对话路径', 'string', 1, 100),
('agent.ai.providers.deepseek.models[0].name', 'deepseek-v4-flash', 'DeepSeek 文本模型', 'string', 1, 100),
('agent.ai.providers.deepseek.models[0].type', 'TEXT', 'DeepSeek 模型类型', 'string', 1, 100),
('agent.ai.providers.deepseek.models[0].multimodal', 'false', 'DeepSeek 模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.deepseek.models[1].name', 'deepseek-v4-pro', 'DeepSeek 文本模型', 'string', 1, 100),
('agent.ai.providers.deepseek.models[1].type', 'TEXT', 'DeepSeek 模型类型', 'string', 1, 100),
('agent.ai.providers.deepseek.models[1].multimodal', 'false', 'DeepSeek 模型是否多模态', 'boolean', 1, 100),
('agent.ai.providers.step.api-style', 'openai', 'Step API 风格', 'string', 1, 100),
('agent.ai.providers.step.base-url', 'https://api.stepfun.com/step_plan/v1', 'Step Base URL', 'string', 1, 100),
('agent.ai.providers.step.completions-path', '/chat/completions', 'Step 对话路径', 'string', 1, 100),
('agent.ai.providers.step.models[0].name', 'step-3.7-flash', 'Step 文本模型', 'string', 1, 100),
('agent.ai.providers.step.models[0].type', 'TEXT', 'Step 模型类型', 'string', 1, 100),
('agent.ai.providers.step.models[0].multimodal', 'false', 'Step 模型是否多模态', 'boolean', 1, 100)
ON DUPLICATE KEY UPDATE `config_key` = VALUES(`config_key`);
