oc:
  jwt:
    issuer: oc # 签发者
    secret: hello_offer # 签名密钥
    expire: 432000000 # jwt的有效期，默认30天
  site:
    login-qr-img: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    website-name: 校招派
    web-site-logo: https://oc.paicoding.com/favicon.ico
    web-site-host: https://oc.paicoding.com
    web-site-url: ${oc.site.web-site-host}
  img:
    abs-tmp-path: /tmp/storage/
    web-img-path: /oc/img/
    cdn-host: https://oc.paicoding.com
  database:
    name: oc
  mainModel: ZhiPu