package com.git.hui.jobclaw.core.agent;

import com.git.hui.jobclaw.core.channel.ChannelReceiveMessage;
import reactor.core.publisher.Flux;

public interface Agent {

    /**
     * Simple text-only interaction (backward compatible)
     */
    String respondTo(String conversationId, String question);

    /**
     * Structured result from agent
     */
    <T> T prompt(String conversationId, String input, Class<T> result);

    /**
     * Stream response from the agent for the given question.
     * Returns a Flux of text chunks that can be consumed reactively.
     *
     * @param conversationId the conversation identifier for memory context
     * @param question the user's question or message
     * @return a Flux emitting text chunks as they are generated by the LLM
     */
    Flux<String> streamResponse(String conversationId, String question);

    /**
     * Multi-modal interaction supporting text, images, files, etc.
     * This is the preferred method for modern multi-modal LLMs.
     *
     * @param conversationId the conversation identifier for memory context
     * @param message the multi-modal message containing text and media
     * @return the agent's text response
     */
    String respondToMultiModal(String conversationId, ChannelReceiveMessage message);
}
