package com.git.hui.jobclaw.core.agent;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import reactor.core.publisher.Flux;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

public interface Agent {

    /**
     * Simple text-only interaction (backward compatible)
     */
    String respondTo(String conversationId, String question);

    /**
     * Structured result from agent
     */
    <T> T prompt(String conversationId, String input, Class<T> result);

    /**
     * Stream response from the agent for the given question.
     * Returns a Flux of text chunks that can be consumed reactively.
     *
     * @param conversationId the conversation identifier for memory context
     * @param question the user's question or message
     * @return a Flux emitting text chunks as they are generated by the LLM
     */
    Flux<String> streamResponse(String conversationId, String question);

    /**
     * Multi-modal interaction supporting text, images, files, etc.
     * This is the preferred method for modern multi-modal LLMs.
     *
     * @param conversationId the conversation identifier for memory context
     * @param message the multi-modal message containing text and media
     * @return the agent's text response
     */
    String respondToMultiModal(String conversationId, MultiModalMessage message);

    /**
     * Represents a multi-modal message that can contain text and various media types.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    class MultiModalMessage {
        private String text;
        @Builder.Default
        private List<ImageContent> images = new ArrayList<>();
        @Builder.Default
        private List<FileContent> files = new ArrayList<>();

        /**
         * Check if this message contains any media (images or files)
         */
        public boolean hasMedia() {
            return !images.isEmpty() || !files.isEmpty();
        }

        /**
         * Build a simple text representation for logging/debugging
         */
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            if (text != null && !text.isEmpty()) {
                sb.append(text);
            }
            if (!images.isEmpty()) {
                sb.append(" [Images: ").append(images.size()).append("]");
            }
            if (!files.isEmpty()) {
                sb.append(" [Files: ").append(files.size()).append("]");
            }
            return sb.toString();
        }
    }

    /**
     * Represents an image in a multi-modal message.
     */
    @Data
    @AllArgsConstructor
    class ImageContent {
        private Path filePath;
        private String mimeType;
        private byte[] data; // Optional: inline image data

        public ImageContent(Path filePath, String mimeType) {
            this.filePath = filePath;
            this.mimeType = mimeType;
            this.data = null;
        }

        public ImageContent(byte[] data, String mimeType) {
            this.filePath = null;
            this.mimeType = mimeType;
            this.data = data;
        }

        public boolean isInline() {
            return data != null;
        }
    }

    /**
     * Represents a file attachment in a multi-modal message.
     */
    @Data
    @AllArgsConstructor
    class FileContent {
        private Path filePath;
        private String fileName;
        private String mimeType;
    }
}
