spring:
  application:
    name: ai-oc
  config:
    import: application-ai.yaml,application-dal.yaml,optional:classpath:application-private.yaml
  web:
    resources:
      # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${jobclaw.img.abs-tmp-path}
        - file:${jobclaw.img.abs-tmp-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB  # 单个文件上传大小限制
      max-request-size: 10MB # 总请求大小限制

  ai:
    mcp:
      server:
        name: 校招派
        protocol: STATELESS
        type: sync
        instructions: "校招派是一个专业的校招信息推荐服务，可以根据您输入的个人求职意愿如求职公司类型、工作地点要求、求职岗位、校招或者实习、毕业年限，自动匹配返回最优的校招信息列表，让你不再错过招聘信息"
        sse-endpoint: /api/sse
        sse-message-endpoint: /api/mcp/messages
        version: 1.0.0
        streamable-http:
          mcp-endpoint: /api/mcp
        capabilities:
          tool: true # 是否支持工具
          resource: true # 是否支持资源
          prompt: true # 是否支持提示词
          completion: true # 是否支持补全

jobclaw:
  jwt:
    issuer: ${JOBCLAW_JWT_ISSUER:jobclaw} # 签发者
    secret: ${JOBCLAW_JWT_SECRET:jobclaw} # 签名密钥
    expire: ${JOBCLAW_JOB_CLAW_JWT_EXPIRE:2592000} # jwt的有效期，默认30天
  site:
    login-qr-img: ${JOBCLAW_SITE_LOGIN_QR_IMG:https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png}
    website-name: ${JOBCLAW_SITE_WEBSITE_NAME:求职派}
    web-site-logo: ${JOBCLAW_SITE_WEBSITE_LOGO:https://oc.paicoding.com/favicon.icon}
    web-site-host: ${JOBCLAW_SITE_WEBSITE_HOST:http://localhost}
    web-site-url: ${oc.site.web-site-host}:${server.port}
  img:
    abs-tmp-path: ${JOBCLAW_IMG_ABS_TMP_PATH:/tmp/storage/}
    web-img-path: ${JOBCLAW_IMG_WEB_IMG_PATH:/oc/img/}
    cdn-host: ${JOBCLAW_IMG_CDN_HOST:http://localhost:8087}
  database:
    name: ${JOBCLAW_DATABASE_NAME:jobclaw}
  mainModel: ${JOBCLAW_MAIN_MODEL:zhipu}
  login:
    wx:
      loginQrType: ${WX_LOGIN_QR_TYPE:SUBSCRIPTION_ACCOUNT} # SUBSCRIPTION_ACCOUNT 表示普通的公众号登录  SERVICE_ACCOUNT 表示服务号关注登录
      appId: ${WX_LOGIN_APP_ID:}
      appSecret: ${WX_LOGIN_APP_SECRET:a7c4xb(使用公众号的appSecret)68c84}
      qrCodeImg: ${WX_LOGIN_QR_IMG:${jobclaw.site.login-qr-img}}
      qrCodeLogo: ${WX_LOGIN_QR_LOGO:${jobclaw.site.web-site-logo}}
      securityCheckToken: ${WX_SECURITY_CHECK_TOKEN:} # 为空，表示不对微信回调的接口进行校验
      subscribeWelcomeInfo: ${WX_LOGIN_SUBSCRIBE_WELCOME_INFO:欢迎来到求职派，请关注公众号，获取更多信息}

pay:
  wx: # 微信支付相关配置
    # true 表示开启微信支付
    enabled: ${WX_PAY_ENABLE:false}
    #应用id（小程序id）
    appId: ${WX_PAY_APP_ID:ww1****3e3}
    #商户号
    merchantId: ${WX_PAY_MERCHANT_ID:162****72}
    #商户API私钥
    privateKey: ${WX_PAY_PRIVATE_KEY:cert/apiclient_key.pem}
    #商户证书序列号
    # openssl x509 -in apiclient_cert.pem -noout -serial
    merchantSerialNumber: ${WX_PAY_MERCHANT_SERIAL_NUMBER:228065B**********F17C37A}
    #商户APIv3密钥
    apiV3Key: ${WX_PAY_API_V3_KEY:Pai******1}
    #支付通知地址
    payNotifyUrl: ${WX_PAY_NOTIFY_URL:https://job.paicoding.cn/api/wx/payNotify}
    #退款通知地址
    refundNotifyUrl: ${WX_PAY_NOTIFY_URL:https://job.paicoding.cn/api/wx/refundNotify}

# agent 的相关配置，通过页面的设置进行引导配置
agent:
  workspace: ${AGENT_WORKSPACE:file:./workspace/}
  context:
    window:
      trim-enabled: ${AGENT_CONTEXT_WINDOW_ENABLED:false}   # 上下文压缩开关
      summary-enabled: ${AGENT_CONTEXT_SUMMARY:false} # 自动提炼会话总结内容开关
      identity-auto-update: ${AGENT_CONTEXT_IDENTITY_AUTO_UPDATE:false} # 自动更新用户身份信息开关
      max-messages: ${AGENT_CONTEXT_MAX_MESSAGES:20} # 最大消息数
      keep-recent: ${AGENT_CONTEXT_KEEP_RECENT:10} # 保留最近消息数
      max-tokens: ${AGENT_CONTEXT_MAX_TOKENS:8000} # Token上限
      filter-short-messages: ${AGENT_CONTEXT_FILTER_SHORT:true} # 过滤短消息
      short-message-threshold: ${AGENT_CONTEXT_SHORT_THRESHOLD:5} # 短消息阈值
      update-identity-frequency: ${AGENT_CONTEXT_UPDATE_identity_FREQUENCY:10} # 更新用户画像的对话频率
  channels:
    wechat:
      clawbot: # 微信的ClawBot Channel配置
        enabled: false
        accounts: { }  # 账号配置，通过页面绑定后自动填充
        cdn-base-url: https://novac2c.cdn.weixin.qq.com/c2c
        base-url: https://ilinkai.weixin.qq.com
    dingding:
      enabled: false
      accounts:
        2: !!seq [ ] # 一个用户支持配置多个机器人
    feishu:
      enabled: false
      accounts:
        2: !!seq [ ]
  tools:
    playwright:
      enabled: true # 是否启用playwright
      headless: true # 是否启用无头模式
  ai:
    preference: # 用户维度的模型配置偏好
      - user-id: 2
        collector: AI_BASED
        channels:
          - wechat-clawbot
          - dingding
        models:
          vision: silicon#PaddlePaddle/PaddleOCR-VL-1.5
          text: silicon#Qwen/Qwen2.5-7B-Instruct
          #          text: zhipu#GLM-4.5-Flash
          providers:
            zhipu:
              api-key: ${ZHIPU_API_KEY:}
              models:
                - GLM-4V-Flash: ${ZHIPU_API_KEY:}
                - GLM-4.7-Flash: ${ZHIPU_API_KEY:}
            silicon:
              api-key: ${SILICON_API_KEY:}

    providers:
      zhipu:
        api-style: openai
        base-url: https://open.bigmodel.cn/api/coding/paas/v4
        completions-path: /chat/completions
        embeddings-path: /embeddings
        images-path: /images/embeddings
        models:
          - name: GLM-4-Flash
            type: TEXT
            multimodal: false
          - name: GLM-4.5-Flash
            type: TEXT
            multimodal: false
          - name: GLM-4.6-Flash
            type: TEXT
            multimodal: false
          - name: GLM-4.7-Flash
            type: TEXT
            multimodal: false
          - name: GLM-4V-Flash
            type: VISION
            multimodal: true
          - name: CogView-3-Flash
            type: IMAGE
            multimodal: false
          - name: CogVideoX-Flash
            type: VIDEO
            multimodal: false
      silicon:
        api-style: openai
        base-url: https://api.siliconflow.cn
        completions-path: /v1/chat/completions
        embeddings-path: /v1/embeddings
        images-path: /v1/images/embeddings
        models:
          - name: Qwen/Qwen2.5-7B-Instruct
            type: TEXT
            multimodal: false
          - name: Qwen/Qwen3.5-4B # 默认开启思考模式
            type: TEXT
            multimodal: false
          - name: Qwen/Qwen3-8B
            type: TEXT
            multimodal: false
          - name: PaddlePaddle/PaddleOCR-VL-1.5
            type: VISION
            multimodal: true
          - name: deepseek-ai/DeepSeek-OCR
            type: VISION
            multimodal: true
          - name: Kwai-Kolors/Kolors
            type: IMAGE
            multimodal: false
          - name: TeleAI/TeleSpeechASR # 语音识别
            type: ASR
            multimodal: false
          - name: FunAudioLLM/SenseVoiceSmall
            type: ASR
            multimodal: false
          - name: BAAI/bge-m3 # 文本向量模型
            type: EMBEDDING
            multimodal: false
          - name: netease-youdao/bce-embedding-base_v1 # 文本向量模型
            type: EMBEDDING
            multimodal: false
          - name: BAAI/bge-large-zh-v1.5
            type: EMBEDDING
            multimodal: false


jobrunr:
  background-job-server:
    enabled: true
    worker-count: 1
  dashboard:
    enabled: true
    port: 8099


# 修改日志级别
logging:
  level:
    com.git.hui: info
    com.git.hui.jobclaw.core.agent.identity: debug

server:
  port: ${JOBCLAW_SERVER_PORT:8087}
  compression:
    enabled: ${JOBCLAW_SERVER_COMPRESSION_ENABLED:true} # 开启返回结果压缩，减少传输耗时
    min-response-size: ${JOBCLAW_SERVER_COMPRESSION_MIN_RESPONSE_SIZE:2KB}

