status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss.SSS}{Asia/Shanghai}][%-5p][%c{1.}] %m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = console

appender.deprecation_console.type = Console
appender.deprecation_console.name = deprecation_console
appender.deprecation_console.layout.type = PatternLayout
appender.deprecation_console.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss.SSS}{Asia/Shanghai}][%-5p][deprecation][%c{1.}] %m%n
appender.deprecation_console.filter.rate_limit.type = RateLimitingFilter

appender.header_warning.type = HeaderWarningAppender
appender.header_warning.name = header_warning

logger.deprecation.name = org.elasticsearch.deprecation
logger.deprecation.level = WARN
logger.deprecation.appenderRef.deprecation_console.ref = deprecation_console
logger.deprecation.appenderRef.header_warning.ref = header_warning
logger.deprecation.additivity = false

appender.index_search_slowlog_console.type = Console
appender.index_search_slowlog_console.name = index_search_slowlog_console
appender.index_search_slowlog_console.layout.type = PatternLayout
appender.index_search_slowlog_console.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss.SSS}{Asia/Shanghai}][%-5p][search-slowlog][%c{1.}] %m%n

logger.index_search_slowlog.name = index.search.slowlog
logger.index_search_slowlog.level = trace
logger.index_search_slowlog.appenderRef.index_search_slowlog_console.ref = index_search_slowlog_console
logger.index_search_slowlog.additivity = false

appender.index_indexing_slowlog_console.type = Console
appender.index_indexing_slowlog_console.name = index_indexing_slowlog_console
appender.index_indexing_slowlog_console.layout.type = PatternLayout
appender.index_indexing_slowlog_console.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss.SSS}{Asia/Shanghai}][%-5p][indexing-slowlog][%c{1.}] %m%n

logger.index_indexing_slowlog.name = index.indexing.slowlog.index
logger.index_indexing_slowlog.level = trace
logger.index_indexing_slowlog.appenderRef.index_indexing_slowlog_console.ref = index_indexing_slowlog_console
logger.index_indexing_slowlog.additivity = false

logger.org_apache_pdfbox.name = org.apache.pdfbox
logger.org_apache_pdfbox.level = off

logger.org_apache_poi.name = org.apache.poi
logger.org_apache_poi.level = off

logger.org_apache_fontbox.name = org.apache.fontbox
logger.org_apache_fontbox.level = off

logger.org_apache_xmlbeans.name = org.apache.xmlbeans
logger.org_apache_xmlbeans.level = off

logger.com_amazonaws.name = com.amazonaws
logger.com_amazonaws.level = warn

