oc:
  jwt:
    issuer: oc # 签发者
    secret: hello_offer # 签名密钥
    expire: 2592000000 # jwt的有效期，默认30天
  site:
    login-qr-img: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    website-name: 校招派
    web-site-logo: https://oc.paicoding.com/favicon.icon
    web-site-host: http://localhost
    web-site-url: ${oc.site.web-site-host}:${server.port}
  img:
    abs-tmp-path: /tmp/storage/
    web-img-path: /oc/img/
    cdn-host: http://localhost:8087
  database:
    name: ai-oc
  mainModel: SparkLite
  wx:
    loginQrType: SUBSCRIPTION_ACCOUNT # SUBSCRIPTION_ACCOUNT 表示普通的公众号登录  SERVICE_ACCOUNT 表示服务号关注登录
    appId: wx59x(使用公众号的appId)ffb8
    appSecret: a7c4xb(使用公众号的appSecret)68c84
    qrCodeImg: ${oc.site.login-qr-img}
    qrCodeLogo: ${oc.site.web-site-logo}
    securityCheckToken: # 为空，表示不对微信回调的接口进行校验
    subscribeWelcomeInfo: 欢迎订阅派聪明服务号